# Generated by Django 5.0.3 on 2024-04-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTGGTA9HaRdJ061vUclkH21iUOcK-Fn4oJAg&s', max_length=1000),
        ),
    ]
